# Generated by Django 5.2.8 on 2025-12-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date_published', 'title']},
        ),
        migrations.AddField(
            model_name='publication',
            name='article_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
